services:
  tuspacio-postgres:
    image: postgres:17
    container_name: tuspacio-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: tuspacio
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  tuspacio-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tuspacio-pgadmin
    restart: always
    depends_on:
      - tuspacio-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  default:
    name: local-network
    external: false
